update=17/12/2017 23:40:51
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName31=C:/Program Files/KiCad/share/kicad/library/74xx
LibName32=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName33=C:/Program Files/KiCad/share/kicad/library/actel
LibName34=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName35=C:/Program Files/KiCad/share/kicad/library/allegro
LibName36=C:/Program Files/KiCad/share/kicad/library/Altera
LibName37=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName38=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName39=C:/Program Files/KiCad/share/kicad/library/arduino_micro_shield
LibName40=C:/Program Files/KiCad/share/kicad/library/arduino_shieldsNCL
LibName41=C:/Program Files/KiCad/share/kicad/library/atmel
LibName42=C:/Program Files/KiCad/share/kicad/library/audio
LibName43=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName44=C:/Program Files/KiCad/share/kicad/library/bbd
LibName45=C:/Program Files/KiCad/share/kicad/library/bosch
LibName46=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName47=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName48=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName49=C:/Program Files/KiCad/share/kicad/library/conn
LibName50=C:/Program Files/KiCad/share/kicad/library/contrib
LibName51=C:/Program Files/KiCad/share/kicad/library/cypress
LibName52=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName53=C:/Program Files/KiCad/share/kicad/library/device
LibName54=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName55=C:/Program Files/KiCad/share/kicad/library/diode
LibName56=C:/Program Files/KiCad/share/kicad/library/display
LibName57=C:/Program Files/KiCad/share/kicad/library/dsp
LibName58=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName59=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName60=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName61=C:/Program Files/KiCad/share/kicad/library/gennum
LibName62=C:/Program Files/KiCad/share/kicad/library/graphic
LibName63=C:/Program Files/KiCad/share/kicad/library/hc11
LibName64=C:/Program Files/KiCad/share/kicad/library/intel
LibName65=C:/Program Files/KiCad/share/kicad/library/interface
LibName66=C:/Program Files/KiCad/share/kicad/library/intersil
LibName67=C:/Program Files/KiCad/share/kicad/library/ir
LibName68=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName69=C:/Program Files/KiCad/share/kicad/library/leds
LibName70=C:/Program Files/KiCad/share/kicad/library/linear
LibName71=C:/Program Files/KiCad/share/kicad/library/logo
LibName72=C:/Program Files/KiCad/share/kicad/library/maxim
LibName73=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName74=C:/Program Files/KiCad/share/kicad/library/memory
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName77=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName78=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName79=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName80=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName81=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName82=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName83=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName84=C:/Program Files/KiCad/share/kicad/library/modules
LibName85=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName86=C:/Program Files/KiCad/share/kicad/library/motorola
LibName87=C:/Program Files/KiCad/share/kicad/library/motors
LibName88=C:/Program Files/KiCad/share/kicad/library/msp430
LibName89=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName90=C:/Program Files/KiCad/share/kicad/library/nxp
LibName91=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName92=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName93=C:/Program Files/KiCad/share/kicad/library/opto
LibName94=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName95=C:/Program Files/KiCad/share/kicad/library/philips
LibName96=C:/Program Files/KiCad/share/kicad/library/power
LibName97=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName98=C:/Program Files/KiCad/share/kicad/library/powerint
LibName99=C:/Program Files/KiCad/share/kicad/library/pspice
LibName100=C:/Program Files/KiCad/share/kicad/library/references
LibName101=C:/Program Files/KiCad/share/kicad/library/regul
LibName102=C:/Program Files/KiCad/share/kicad/library/relays
LibName103=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName104=C:/Program Files/KiCad/share/kicad/library/sensors
LibName105=C:/Program Files/KiCad/share/kicad/library/silabs
LibName106=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName107=C:/Program Files/KiCad/share/kicad/library/stm8
LibName108=C:/Program Files/KiCad/share/kicad/library/stm32
LibName109=C:/Program Files/KiCad/share/kicad/library/supertex
LibName110=C:/Program Files/KiCad/share/kicad/library/switches
LibName111=C:/Program Files/KiCad/share/kicad/library/texas
LibName112=C:/Program Files/KiCad/share/kicad/library/transf
LibName113=C:/Program Files/KiCad/share/kicad/library/transistors
LibName114=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName115=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName116=C:/Program Files/KiCad/share/kicad/library/valves
LibName117=C:/Program Files/KiCad/share/kicad/library/video
LibName118=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName119=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName120=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName121=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName122=C:/Program Files/KiCad/share/kicad/library/zetex
LibName123=C:/Program Files/KiCad/share/kicad/library/Zilog
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=Beating Signal7.net
PadDrill=0
PadDrillOvalY=0
PadSizeH=3
PadSizeV=24
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[general]
version=1
